<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.sota</groupId>
    <artifactId>crud</artifactId>
    <packaging>pom</packaging>
    <version>1.0.0</version>

    <distributionManagement>
        <repository>
            <id>acquanet-central</id>
            <name>Acquanet Central Repository</name>
            <url>http://157.245.236.175:8081/artifactory/libs-release</url>
        </repository>
    </distributionManagement>

    <modules>
        <module>add-on</module>
        <module>crud-ui-demo</module>
    </modules>

</project>
